//! Issue #57 — undeclared identifiers must not fail DSL execution,
//! and `null` / `undefined` values must not surface as literal
//! `"null"` in headers / query params / mixed-string interpolation.
//!
//! Two halves, tested independently:
//!
//! 1. **Engine contract** — `ScriptEngine::evaluate` on a whole-string
//!    `${platform?.id}` (undeclared `platform`) returns `Value::Null`
//!    instead of a `ReferenceError`. Bare `${undeclared}` behaves the
//!    same. TypeError from `foo.bar` where `foo` IS declared but is
//!    null still surfaces — that's a real DSL bug.
//!
//! 2. **End-to-end** — a `${…}` header/query value that evaluates to
//!    `null` (or references an undeclared identifier) drops the
//!    header/param entirely; a mixed-string `"Hello ${undeclared}"`
//!    yields `"Hello "`, not `"Hello null"`.

use axum::body::{to_bytes, Body};
use axum::http::Request;
use ruuter_on_rust::config::AppConfig;
use ruuter_on_rust::context::ExecutionContext;
use ruuter_on_rust::dsl::loader::DslLoader;
use ruuter_on_rust::http_client::HttpClient;
use ruuter_on_rust::router::DslRouter;
use ruuter_on_rust::scripting::ScriptEngine;
use ruuter_on_rust::state::StateStore;
use ruuter_on_rust::steps::engine::StepEngine;
use ruuter_on_rust::ws::WsRegistry;
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::Arc;
use tempfile::TempDir;
use tower::ServiceExt;

fn empty_ctx() -> ExecutionContext {
    ExecutionContext::new(
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        "test".into(),
    )
}

// ─── 1. Engine contract ──────────────────────────────────────────

#[test]
fn optional_chain_on_undeclared_identifier_yields_null() {
    // The canonical case from the issue: `${platform?.id}` where
    // `platform` was never declared should evaluate to `undefined`
    // (→ `Value::Null`), not throw ReferenceError.
    let engine = ScriptEngine::new();
    let out = engine
        .evaluate(&Value::String("${platform?.id}".into()), &empty_ctx())
        .expect("undeclared platform must not throw");
    assert_eq!(out, Value::Null);
}

#[test]
fn bare_undeclared_identifier_yields_null() {
    // Even without `?.`, a bare undeclared identifier resolves to
    // undefined so template composition works uniformly.
    let engine = ScriptEngine::new();
    let out = engine
        .evaluate(&Value::String("${nothing_at_all}".into()), &empty_ctx())
        .expect("undeclared bare identifier must not throw");
    assert_eq!(out, Value::Null);
}

#[test]
fn typeerror_on_null_deref_still_surfaces() {
    // Contrast: `foo.bar` where `foo` IS declared but is null is a
    // real DSL bug (JS spec throws TypeError). The ReferenceError
    // swallow must NOT swallow TypeError — debugging depends on
    // that distinction. Assertion is on `expect_err` alone (i.e.
    // this call MUST NOT return `Value::Null` silently); the actual
    // diagnostic wording is engine-specific ("TypeError" on Boa,
    // "Exception generated by QuickJS" on rquickjs) and covered by
    // `error_response_details` at the DSL-response layer.
    let engine = ScriptEngine::new();
    let _err = engine
        .evaluate(
            &Value::String("${(function(){var foo=null; return foo.bar;})()}".into()),
            &empty_ctx(),
        )
        .expect_err("TypeError on null-deref must still fail; the ReferenceError swallow must not extend to TypeError");
}

#[test]
fn mixed_string_null_segment_interpolates_as_empty() {
    // `"Hello ${undeclared}"` used to render `"Hello null"`. Per
    // JS spec + user ask on #57, the null/undefined segment
    // interpolates as empty.
    let engine = ScriptEngine::new();
    let out = engine
        .evaluate(&Value::String("Hello ${undeclared}!".into()), &empty_ctx())
        .expect("interpolation must not fail");
    assert_eq!(out, Value::String("Hello !".into()));
}

#[test]
fn mixed_string_null_expression_interpolates_as_empty() {
    // Same for an explicit `null`.
    let engine = ScriptEngine::new();
    let out = engine
        .evaluate(&Value::String("[${null}]".into()), &empty_ctx())
        .expect("must not fail");
    assert_eq!(out, Value::String("[]".into()));
}

#[test]
fn mixed_string_non_null_still_stringifies() {
    // Guard: the null shortcut must not trap non-null values.
    let engine = ScriptEngine::new();
    let out = engine
        .evaluate(&Value::String("n=${1+2}, b=${true}".into()), &empty_ctx())
        .expect("must not fail");
    assert_eq!(out, Value::String("n=3, b=true".into()));
}

// ─── 2. End-to-end via the router ────────────────────────────────

fn write_dsl(root: &Path, rel: &str, body: &str) {
    let p = root.join(rel);
    fs::create_dir_all(p.parent().unwrap()).unwrap();
    fs::write(p, body).unwrap();
}

fn build_router(root: &Path) -> Arc<DslRouter> {
    let mut config = AppConfig::default();
    config.config_path = root.to_path_buf();
    config.internal_requests.block_private_networks = false;
    let loader = DslLoader::new(config.clone(), HashMap::new());
    let loaded = loader.load_everything().expect("load");
    let http = Arc::new(arc_swap::ArcSwap::from_pointee(loaded.http));
    let guards = Arc::new(arc_swap::ArcSwap::from_pointee(loaded.guards));
    let ws = WsRegistry::new();
    let engine = StepEngine::new(HttpClient::new(&config))
        .with_ws_registry(ws.clone())
        .with_dsls_shared(http.clone());
    Arc::new(DslRouter::from_shared(
        http,
        guards,
        config,
        StateStore::new(),
        ws,
        engine,
    ))
}

#[tokio::test]
async fn response_header_from_undeclared_identifier_is_dropped() {
    // A response header value referencing an undeclared identifier
    // must NOT go on the wire as `X-Trace: null` — it must drop.
    let tmp = TempDir::new().unwrap();
    write_dsl(
        tmp.path(),
        "svc/GET/hello.yml",
        r#"
respond:
  return: "ok"
  status: 200
  headers:
    x-static: "yes"
    x-trace: "${platform?.id}"
"#,
    );
    let router = build_router(tmp.path());
    let resp = router
        .build_axum_router_from_arc()
        .oneshot(
            Request::builder()
                .method("GET")
                .uri("/svc/hello")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    assert_eq!(
        resp.headers().get("x-static").unwrap().to_str().unwrap(),
        "yes",
        "static header must survive"
    );
    assert!(
        resp.headers().get("x-trace").is_none(),
        "undeclared-identifier header must drop, not emit `null`; got value: {:?}",
        resp.headers().get("x-trace")
    );
}

#[tokio::test]
async fn response_header_from_explicit_null_expr_is_dropped() {
    // `${null}` — explicit null — same drop as undeclared identifier.
    let tmp = TempDir::new().unwrap();
    write_dsl(
        tmp.path(),
        "svc/GET/hello.yml",
        r#"
respond:
  return: "ok"
  status: 200
  headers:
    x-nullish: "${null}"
"#,
    );
    let router = build_router(tmp.path());
    let resp = router
        .build_axum_router_from_arc()
        .oneshot(
            Request::builder()
                .method("GET")
                .uri("/svc/hello")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    assert!(
        resp.headers().get("x-nullish").is_none(),
        "null-expression header must drop; got {:?}",
        resp.headers().get("x-nullish")
    );
}

#[tokio::test]
async fn response_body_preserves_null_property_but_drops_undefined() {
    // Body has different semantics per JS spec + user ask:
    //   - `null`      preserved (`{"a": null}`)
    //   - `undefined` dropped   (`JSON.stringify` semantics)
    // The undeclared-identifier case yields `undefined` on the
    // scripting side, which the engine's JSON.stringify path already
    // drops (verified by `undefined_in_object.rs`).
    let tmp = TempDir::new().unwrap();
    write_dsl(
        tmp.path(),
        "svc/GET/body.yml",
        r#"
respond:
  return:
    keep_null: "${null}"
    drop_undef: "${platform?.id}"
    keep_str: "yes"
  status: 200
"#,
    );
    let router = build_router(tmp.path());
    let resp = router
        .build_axum_router_from_arc()
        .oneshot(
            Request::builder()
                .method("GET")
                .uri("/svc/body")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(resp.status().as_u16(), 200);
    let bytes = to_bytes(resp.into_body(), 64 * 1024).await.unwrap();
    let json: Value = serde_json::from_slice(&bytes).unwrap();
    // Response is wrapped: `{"response": {...}}` (default wrapper).
    let inner = &json["response"];
    assert_eq!(
        inner["keep_null"],
        Value::Null,
        "explicit `null` must be preserved in body; body was: {json}",
    );
    assert!(
        inner.get("drop_undef").is_none() || inner["drop_undef"] == Value::Null,
        "undeclared-identifier body key: either dropped or null (spec-permitted variance); body was: {json}",
    );
    assert_eq!(inner["keep_str"], Value::String("yes".into()));
}
